In [1]:
import numpy as np

In [2]:
a = np.array([0,1], dtype=np.int64)

In [3]:
n = 3

In [4]:
flip_list = np.meshgrid(*(a,)*n)

In [5]:
print(flip_list)

[array([[[0, 0],
        [1, 1]],

       [[0, 0],
        [1, 1]]], dtype=int64), array([[[0, 0],
        [0, 0]],

       [[1, 1],
        [1, 1]]], dtype=int64), array([[[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]], dtype=int64)]


In [6]:
flip_list[0].shape

(2, 2, 2)

In [8]:
tmp = np.transpose(np.stack((x.flatten() for x in flip_list)))

In [9]:
print(tmp)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


In [10]:
tmp.shape

(8, 3)

In [11]:
np.zeros(np.power(2, n), dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
import numpy as np

In [10]:
type(np.zeros(12)).__name__ == 'ndarray'

True

In [11]:
a = np.zeros((123,12))

In [12]:
b = np.zeros((123, 12))

In [13]:
a.shape == b.shape

True